src/Entity/Candidature.php
<?php

namespace App\Entity;

use App\Repository\CandidatureRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CandidatureRepository::class)]
class Candidature
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_candidature = null;

    #[ORM\Column]
    private ?bool $cv = null;

    #[ORM\Column]
    private ?bool $lettre_motivation = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_relance = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $entretien = null;

    #[ORM\Column(length: 255)]
    private ?string $status = null;

    #[ORM\ManyToOne(inversedBy: 'candidatures')]
    private ?Offre $offre = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateCandidature(): ?\DateTimeInterface
    {
        return $this->date_candidature;
    }

    public function setDateCandidature(\DateTimeInterface $date_candidature): static
    {
        $this->date_candidature = $date_candidature;

        return $this;
    }

    public function getDateCandidatureFr(): ?string
    {
        return $this->date_candidature->format("d-m-Y");
    }

    public function isCv(): ?bool
    {
        return $this->cv;
    }

    public function setCv(bool $cv): static
    {
        $this->cv = $cv;

        return $this;
    }

    public function isLettreMotivation(): ?bool
    {
        return $this->lettre_motivation;
    }

    public function setLettreMotivation(bool $lettre_motivation): static
    {
        $this->lettre_motivation = $lettre_motivation;

        return $this;
    }

    public function getDateRelance(): ?\DateTimeInterface
    {
        return $this->date_relance;
    }

    public function getDateRelanceFr(): ?string
    {
        return $this->date_candidature->format("d-m-Y");
    }

    public function setDateRelance(?\DateTimeInterface $date_relance): static
    {
        $this->date_relance = $date_relance;

        return $this;
    }

    public function getEntretien(): ?string
    {
        return $this->entretien;
    }

    public function setEntretien(?string $entretien): static
    {
        $this->entretien = $entretien;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getOffre(): ?Offre
    {
        return $this->offre;
    }

    public function setOffre(?Offre $offre): static
    {
        $this->offre = $offre;

        return $this;
    }

    // public function candidatureParSemaine(){

    // }

    // public function candidatureParMois(){
        
    // }
}

src/Entity/Entreprise.php
<?php

namespace App\Entity;

use App\Repository\EntrepriseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EntrepriseRepository::class)]
class Entreprise
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_entreprise = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $lien_entreprise = null;

    #[ORM\Column(nullable: true)]
    private ?int $siret = null;

    #[ORM\OneToMany(targetEntity: Offre::class, mappedBy: 'entreprise')]
    private Collection $offres;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $adresse = null;

    public function __construct()
    {
        $this->offres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomEntreprise(): ?string
    {
        return $this->nom_entreprise;
    }

    public function setNomEntreprise(string $nom_entreprise): static
    {
        $this->nom_entreprise = $nom_entreprise;

        return $this;
    }

    public function getLienEntreprise(): ?string
    {
        return $this->lien_entreprise;
    }

    public function setLienEntreprise(?string $lien_entreprise): static
    {
        $this->lien_entreprise = $lien_entreprise;

        return $this;
    }

    public function getSiret(): ?int
    {
        return $this->siret;
    }

    public function setSiret(?int $siret): static
    {
        $this->siret = $siret;

        return $this;
    }

    /**
     * @return Collection<int, Offre>
     */
    public function getOffres(): Collection
    {
        return $this->offres;
    }

    public function addOffre(Offre $offre): static
    {
        if (!$this->offres->contains($offre)) {
            $this->offres->add($offre);
            $offre->setEntreprise($this);
        }

        return $this;
    }

    public function removeOffre(Offre $offre): static
    {
        if ($this->offres->removeElement($offre)) {
            // set the owning side to null (unless already changed)
            if ($offre->getEntreprise() === $this) {
                $offre->setEntreprise(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->nom_entreprise;   
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }
}

src/Entity/Offre.php
<?php

namespace App\Entity;

use App\Repository\OffreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OffreRepository::class)]
class Offre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $numero = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $lieu_travail = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $diffusion = null;

    #[ORM\Column(length: 255)]
    private ?string $salaire = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $lien_offre = null;

    #[ORM\ManyToOne(inversedBy: 'offres')]
    private ?Entreprise $entreprise = null;

    #[ORM\OneToMany(targetEntity: Candidature::class, mappedBy: 'offre')]
    private Collection $candidatures;

    #[ORM\ManyToOne(inversedBy: 'offres')]
    private ?Referent $referent = null;

    public function __construct()
    {
        $this->candidatures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumero(): ?string
    {
        return $this->numero;
    }

    public function setNumero(?string $numero): static
    {
        $this->numero = $numero;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getLieuTravail(): ?string
    {
        return $this->lieu_travail;
    }

    public function setLieuTravail(string $lieu_travail): static
    {
        $this->lieu_travail = $lieu_travail;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDiffusion(): ?string
    {
        return $this->diffusion;
    }

    public function setDiffusion(?string $diffusion): static
    {
        $this->diffusion = $diffusion;

        return $this;
    }

    public function getSalaire(): ?string
    {
        return $this->salaire;
    }

    public function setSalaire(string $salaire): static
    {
        $this->salaire = $salaire;

        return $this;
    }

    public function getLienOffre(): ?string
    {
        return $this->lien_offre;
    }

    public function setLienOffre(?string $lien_offre): static
    {
        $this->lien_offre = $lien_offre;

        return $this;
    }

    public function getEntreprise(): ?Entreprise
    {
        return $this->entreprise;
    }

    public function setEntreprise(?Entreprise $entreprise): static
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    /**
     * @return Collection<int, Candidature>
     */
    public function getCandidatures(): Collection
    {
        return $this->candidatures;
    }

    public function addCandidature(Candidature $candidature): static
    {
        if (!$this->candidatures->contains($candidature)) {
            $this->candidatures->add($candidature);
            $candidature->setOffre($this);
        }

        return $this;
    }

    public function removeCandidature(Candidature $candidature): static
    {
        if ($this->candidatures->removeElement($candidature)) {
            // set the owning side to null (unless already changed)
            if ($candidature->getOffre() === $this) {
                $candidature->setOffre(null);
            }
        }

        return $this;
    }

    public function getReferent(): ?Referent
    {
        return $this->referent;
    }

    public function setReferent(?Referent $referent): static
    {
        $this->referent = $referent;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Candidature;
use App\Repository\CandidatureRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class HomeController extends AbstractController
{
    #[Route('/home', name: 'app_home')]
    public function index(CandidatureRepository $candidatureRepository): Response
    {
        $candidatures = $candidatureRepository->findAll();
        return $this->render('home/index.html.twig', [
            'candidatures' => $candidatures
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block body %}
    {{ parent() }}
    <div class="container container-fluid">
        <h1><span style="color:blue">Job</span>Trackr, l'outil qui vous permet de gérer vos candidatures</h1>
            <table class="table table-striped table-bordered border-dark">
                <thead>
                  <tr colspan="2">
                    {# offre #}
                    <th scope="col">#</th>
                    <th scope="col" colspan="2">Offre</th>
                    <th scope="col">Entreprise</th>
                    <th scope="col" colspan="2">Candidature</th>
                  </tr>
                </thead>
                <tbody>
                  {% for candidature in candidatures %}
                    <tr>
                      <th scope="row">{{ loop.index }}</th>
                      {# offre #}
                      <td><a href="{{ candidature.offre.lienOffre }}">{{ candidature.offre.titre }}</a></td>
                      <td>📍 {{ candidature.offre.lieuTravail }}</td>
                      <td><a href="{{ candidature.offre.entreprise.lienEntreprise }}">{{ candidature.offre.entreprise }}</a></td>
                      <td>Date de candidature : {{ candidature.dateCandidatureFr }}</td>
                      <td>{{ candidature.status }}</td>
                    </tr>
                    <tr>
                      <th scope="row"></th>
                      <td>{{ candidature.offre.description }}</td>
                      <td>💸 {{ candidature.offre.salaire }}€/an</td>
                      <td>{{ candidature.offre.entreprise.adresse }}</td>
                      <td>
                        {% if candidature.dateRelance %}
                          Relance : {{ candidature.dateRelanceFr }}</td>
                        {% else %}
                          Pas encore relancé
                        {% endif %}
                      <td><a href="" class="btn btn-dark"><span class="material-symbols-outlined">
                        edit
                        </span></a><br>
                        <a href="{{ path('delete_candidature', {id: candidature.id}) }}" class="btn btn-dark"><span class="material-symbols-outlined">
                          delete
                          </span></a></td>
                    </tr>
                  {% endfor %}
            
                </tbody>
              </table>
              {# <a href="{{ path('app_candidature') }}" class="btn btn-dark">Voir toutes les candidatures</a> #}
              <a href="{{ path('new_candidature') }}" class="btn btn-dark">Ajouter une candidature</a>
    </div>



   {# <div class="container text-center">
        <div class="row">
          <div class="col">
            <h2>Aperçu des candidatures</h2>
            <table class="table table-striped table-bordered border-dark">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Titre</th>
                    <th scope="col">Entreprise</th>
                    <th scope="col">Lieu</th>
                    <th scope="col">Salaire</th>
                    <th scope="col">Date de candidature</th>
                    <th scope="col">Status</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row">1</th>
                    <td>Développeur web</td>
                    <td>Entreprise</td>
                    <td>Strasbourg</td>
                    <td>10K/an</td>
                    <td>21.02.2024</td>
                    <td>En attente</td>
                  </tr>
            
                </tbody>
              </table>
              <a href="">Voir toutes les candidatures</a>
              <a href="">Ajouter une candidature</a>
          </div>
          <div class="col">
            <h3>Aperç des entreprises</h3>
            <table class="table table-striped table-bordered border-dark">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">First</th>
                    <th scope="col">Last</th>
                    <th scope="col">Handle</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row">1</th>
                    <td>Mark</td>
                    <td>Otto</td>
                    <td>@mdo</td>
                  </tr>
                </tbody>
              </table>
              <a href="">Voir toutes les entreprises</a>
              <a href="">Ajouter une entreprise</a>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <table class="table table-striped table-bordered border-dark">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">First</th>
                    <th scope="col">Last</th>
                    <th scope="col">Handle</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row">1</th>
                    <td>Mark</td>
                    <td>Otto</td>
                    <td>@mdo</td>
                  </tr>
                  <tr>
                    <th scope="row">2</th>
                    <td>Jacob</td>
                    <td>Thornton</td>
                    <td>@fat</td>
                  </tr>
                  <tr>
                    <th scope="row">3</th>
                    <td colspan="2">Larry the Bird</td>
                    <td>@twitter</td>
                  </tr>
                </tbody>
              </table>
              <a href="">Ajouter une offre</a>
          </div>
          <div class="col">
            <table class="table table-striped table-bordered border-dark">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">First</th>
                    <th scope="col">Last</th>
                    <th scope="col">Handle</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row">1</th>
                    <td>Mark</td>
                    <td>Otto</td>
                    <td>@mdo</td>
                  </tr>
                  <tr>
                    <th scope="row">2</th>
                    <td>Jacob</td>
                    <td>Thornton</td>
                    <td>@fat</td>
                  </tr>
                  <tr>
                    <th scope="row">3</th>
                    <td colspan="2">Larry the Bird</td>
                    <td>@twitter</td>
                  </tr>
                </tbody>
              </table>
              <a href="">Ajouter un contact</a>
          </div>
          <div class="col">
            <table class="table table-striped table-bordered border-dark">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">First</th>
                    <th scope="col">Last</th>
                    <th scope="col">Handle</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row">1</th>
                    <td>Mark</td>
                    <td>Otto</td>
                    <td>@mdo</td>
                  </tr>
                  <tr>
                    <th scope="row">2</th>
                    <td>Jacob</td>
                    <td>Thornton</td>
                    <td>@fat</td>
                  </tr>
                  <tr>
                    <th scope="row">3</th>
                    <td colspan="2">Larry the Bird</td>
                    <td>@twitter</td>
                  </tr>
                </tbody>
              </table>
          </div>
        </div>
      </div>  #}
{% endblock %}